development:
  adapter: postgresql
  encoding: unicode
  database: blogger_development
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: blogger_test
  host: localhost
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: blogger_production
  host: localhost
  pool: 5
  username: postgres
  password: root
